### ISSUE TITLE
Applications Has Stopped

### ISSUE THREAD

**Issue by vianziro** [rakaadinugroho/Elearning-Mobile#2]
ketika di running dan pas login selalu close aplication, (has stopped)

**Comment by rakaadinugroho** [comment]
cek terlebih dahulu servicenya, misalkan menggunakan POSTMAN atau tools lain:)

**Comment by msyihabudin** [comment]
Mau tanya juga mas @rakaadinugroho, kalo pas running langsung "has stopped" itu kenapa ya? servicenya udah di coba di POSTMAN jalan...

**Comment by rakaadinugroho** [comment]
logcat errornya kayak apa ?

**Comment by msyihabudin** [comment]
Kaya gini mas @rakaadinugroho logcat errornya..
`FATAL EXCEPTION: main
Process: com.rakaadinugroho.msuryanusatara, PID: 4716
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rakaadinugroho.msuryanusatara/com.rakaadinugroho.msuryanusatara.core.authentication.AuthActivity}: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                     at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                  Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported`

**Comment by rakaadinugroho** [comment]
oh MODE_WORLD_READABLE, Versi OSnya yang dipakai Nougat keatas ya di HP/Atau Emulator ? di bagian **SessionManager** untuk Sharedpreferences nya gunakan **0** mode nya bukan **1**

**Comment by msyihabudin** [comment]
Terima kasih mas sudah bisa..
Tapi pas login muncul `Error: Http 404 Not Found`

**Comment by rakaadinugroho** [comment]
cek lagi endpointya. sudah diganti BASE URLnya sama base url Anda ?

**Comment by msyihabudin** [comment]
Udah disesuain mas BASE URL-nya..
Error logcat nya gini:
`E/dalvikvm: Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.AppCompatImageHelper.hasOverlappingRendering`

**Comment by msyihabudin** [comment]
Sudah bisa ternyata karna api nya local, setelah di hosting baru bisa...

**Comment by skill347** [comment]
mas di android pas login muncul Error: Http 404 Not Found padahal base url nya udah diganti, api nya juga udah di hosting, kenapa ya ?
